/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package control_domotico;

/**
 *
 * @author teller
 */
public class Mapa extends javax.swing.JFrame {

    /**
     * Creates new form Mapa
     */
    public Ventana_Luz ventana = new Ventana_Luz();
    
    public Ventana_Despertador ventana_despertador = new Ventana_Despertador();
    
    public Ventana_Baniera ventana_baniera = new Ventana_Baniera();
    
    public Ventana_llave ventana_llave = new Ventana_llave();
    
    public Ventana_Lavadora ventana_lavadora = new Ventana_Lavadora();

    public Ventana_Aspiradora ventana_aspirador = new Ventana_Aspiradora();
    
    public Ventana_Vitro ventana_vitro = new Ventana_Vitro();
    
    public Ventana_Aire ventana_aire = new Ventana_Aire();
    
    public Ventana_Cafetera ventana_cafetera = new Ventana_Cafetera(); 
    
    public Ventana_tv ventana_tv = new Ventana_tv();
    public Mapa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Atras = new javax.swing.JButton();
        Baniera = new javax.swing.JButton();
        Lampara_h3 = new javax.swing.JButton();
        lampara_cocina = new javax.swing.JButton();
        lampara_h1 = new javax.swing.JButton();
        lampara_terraza = new javax.swing.JButton();
        lampara_h2 = new javax.swing.JButton();
        lavadora = new javax.swing.JButton();
        Llave = new javax.swing.JButton();
        Cafetera = new javax.swing.JButton();
        Aspirador = new javax.swing.JButton();
        Llave1 = new javax.swing.JButton();
        despertador = new javax.swing.JButton();
        tv = new javax.swing.JButton();
        olla = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(670, 460));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setMinimumSize(new java.awt.Dimension(1137, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1137, 500));
        jPanel1.setLayout(null);

        Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/volver-flecha-azul-a-la-izquierda-icono-8990-128.png"))); // NOI18N
        Atras.setBorder(null);
        Atras.setBorderPainted(false);
        Atras.setContentAreaFilled(false);
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        jPanel1.add(Atras);
        Atras.setBounds(0, -2, 130, 130);

        Baniera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/bañera2.png"))); // NOI18N
        Baniera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BanieraActionPerformed(evt);
            }
        });
        jPanel1.add(Baniera);
        Baniera.setBounds(420, 330, 30, 30);

        Lampara_h3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lampara2.png"))); // NOI18N
        Lampara_h3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lampara_h3ActionPerformed(evt);
            }
        });
        jPanel1.add(Lampara_h3);
        Lampara_h3.setBounds(590, 290, 40, 30);

        lampara_cocina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lampara2.png"))); // NOI18N
        lampara_cocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lampara_cocinaActionPerformed(evt);
            }
        });
        jPanel1.add(lampara_cocina);
        lampara_cocina.setBounds(290, 150, 40, 30);

        lampara_h1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lampara2.png"))); // NOI18N
        lampara_h1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lampara_h1ActionPerformed(evt);
            }
        });
        jPanel1.add(lampara_h1);
        lampara_h1.setBounds(430, 180, 40, 30);

        lampara_terraza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lampara2.png"))); // NOI18N
        lampara_terraza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lampara_terrazaActionPerformed(evt);
            }
        });
        jPanel1.add(lampara_terraza);
        lampara_terraza.setBounds(210, 260, 40, 30);

        lampara_h2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lampara2.png"))); // NOI18N
        lampara_h2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lampara_h2ActionPerformed(evt);
            }
        });
        jPanel1.add(lampara_h2);
        lampara_h2.setBounds(520, 180, 40, 30);

        lavadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lavadora2.png"))); // NOI18N
        lavadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lavadoraActionPerformed(evt);
            }
        });
        jPanel1.add(lavadora);
        lavadora.setBounds(220, 10, 40, 40);

        Llave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Llave2.png"))); // NOI18N
        Llave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LlaveActionPerformed(evt);
            }
        });
        jPanel1.add(Llave);
        Llave.setBounds(470, 70, 30, 30);

        Cafetera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cafetera2.png"))); // NOI18N
        Cafetera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CafeteraActionPerformed(evt);
            }
        });
        jPanel1.add(Cafetera);
        Cafetera.setBounds(210, 150, 40, 40);

        Aspirador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/aspirador2.png"))); // NOI18N
        Aspirador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AspiradorActionPerformed(evt);
            }
        });
        jPanel1.add(Aspirador);
        Aspirador.setBounds(330, 230, 40, 40);

        Llave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Llave2.png"))); // NOI18N
        Llave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Llave1ActionPerformed(evt);
            }
        });
        jPanel1.add(Llave1);
        Llave1.setBounds(440, 140, 30, 30);

        despertador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/despertador2.png"))); // NOI18N
        despertador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despertadorActionPerformed(evt);
            }
        });
        jPanel1.add(despertador);
        despertador.setBounds(570, 210, 40, 40);

        tv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/televisor2.png"))); // NOI18N
        tv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvActionPerformed(evt);
            }
        });
        jPanel1.add(tv);
        tv.setBounds(360, 310, 40, 30);

        olla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/olla2.png"))); // NOI18N
        olla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ollaActionPerformed(evt);
            }
        });
        jPanel1.add(olla);
        olla.setBounds(210, 200, 40, 40);

        jLabel13.setText("Llave");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(50, 170, 120, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Logo_1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(530, 10, 110, 120);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lampara2.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 130, 40, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Llave2.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 160, 40, 30);

        jLabel14.setText("Bañera");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(50, 200, 120, 14);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/bañera2.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 190, 40, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cafetera2.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 220, 40, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/despertador2.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 260, 40, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lavadora2.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 300, 40, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/olla2.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 340, 40, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/televisor2.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 400, 40, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/aspirador2.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 370, 40, 30);

        jLabel12.setText("Luz");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 140, 120, 14);

        jLabel15.setText("Cafetera");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(50, 240, 110, 14);

        jLabel16.setText("Despertador");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(50, 280, 130, 14);

        jLabel17.setText("Lavadora");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(50, 320, 130, 14);

        jLabel18.setText("Vitrocerámica");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(50, 350, 130, 14);

        jLabel19.setText("Aspirador");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(50, 380, 120, 14);

        jLabel20.setText("Television");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(50, 410, 120, 14);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ventilador.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(370, 160, 30, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Plano-de-casa-en-3d.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 10, 535, 386);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ventilador.jpg"))); // NOI18N
        jPanel1.add(jLabel21);
        jLabel21.setBounds(0, 430, 40, 40);

        jLabel22.setText("Aire");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(50, 440, 90, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1137, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        // TODO add your handling code here:
        ventana_anterior.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AtrasActionPerformed

    private void Lampara_h3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lampara_h3ActionPerformed
        // TODO add your handling code here:
        ventana.setVisible(true);
        ventana.aux = this;
        ventana.luz = ventana_anterior.luz_habitacion3;
        ventana.name = "Luz Habitacion 3";
        ventana.actualizar();
        this.setVisible(false);
    }//GEN-LAST:event_Lampara_h3ActionPerformed

    private void lampara_cocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lampara_cocinaActionPerformed
        // TODO add your handling code here:
        ventana.setVisible(true);
        ventana.aux = this;
        ventana.luz = ventana_anterior.luz_cocina;
        ventana.name = "Luz Cocina";
        ventana.actualizar();
        this.setVisible(false);
    }//GEN-LAST:event_lampara_cocinaActionPerformed

    private void lampara_h1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lampara_h1ActionPerformed
        // TODO add your handling code here:
        ventana.setVisible(true);
        ventana.aux = this;
        ventana.luz = ventana_anterior.luz_habitacion1;
        ventana.name = "Luz Habitacion 1";
        ventana.actualizar();
        this.setVisible(false);
    }//GEN-LAST:event_lampara_h1ActionPerformed

    private void lampara_terrazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lampara_terrazaActionPerformed
        // TODO add your handling code here:
        ventana.setVisible(true);
        ventana.aux = this;
        ventana.luz = ventana_anterior.luz_terraza;
        ventana.name = "Luz Terraza";
        ventana.actualizar();
        this.setVisible(false);
    }//GEN-LAST:event_lampara_terrazaActionPerformed

    private void lampara_h2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lampara_h2ActionPerformed
        // TODO add your handling code here:
        ventana.setVisible(true);
        ventana.aux = this;
        ventana.luz = ventana_anterior.luz_habitacion2;
        ventana.name = "Luz Habitacion 2";
        ventana.actualizar();
        this.setVisible(false);
    }//GEN-LAST:event_lampara_h2ActionPerformed

    private void lavadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lavadoraActionPerformed
        // TODO add your handling code here:
        ventana_lavadora.setVisible(true);
        ventana_lavadora.aux = this;
        ventana_lavadora.lavadora = ventana_anterior.lavadora;
        ventana_lavadora.actualizar();
        this.setVisible(false);
    }//GEN-LAST:event_lavadoraActionPerformed

    private void LlaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LlaveActionPerformed
        // TODO add your handling code here:
        ventana_llave.setVisible(true);
        ventana_llave.aux = this;
        ventana_llave.llave = ventana_anterior.llave_cochera;
        ventana_llave.name = "Puerta Cochera";
        ventana_llave.actualizar();
        this.setVisible(false);
    }//GEN-LAST:event_LlaveActionPerformed

    private void Llave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Llave1ActionPerformed
        // TODO add your handling code here:
        ventana_llave.setVisible(true);
        ventana_llave.aux = this;
        ventana_llave.llave = ventana_anterior.llave_casa;
        ventana_llave.name = "Puerta Casa";
        ventana_llave.actualizar();
        this.setVisible(false);
    }//GEN-LAST:event_Llave1ActionPerformed

    private void tvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvActionPerformed
        // TODO add your handling code here:
       ventana_tv.setVisible(true);
        ventana_tv.aux = this;
        ventana_tv.tv = ventana_anterior.tv;
        ventana_tv.actualizar();
        this.setVisible(false);        
    }//GEN-LAST:event_tvActionPerformed

    private void ollaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ollaActionPerformed
        // TODO add your handling code here:
        ventana_vitro.setVisible(true);
        ventana_vitro.aux = this;
        ventana_vitro.vitro = ventana_anterior.vitro;
        ventana_vitro.actualizar();
        this.setVisible(false);
    }//GEN-LAST:event_ollaActionPerformed

    private void despertadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despertadorActionPerformed
        // TODO add your handling code here:
        ventana_despertador.setVisible(true);
        ventana_despertador.aux = this;
        ventana_despertador.despertador = ventana_anterior.despertador;
        ventana_despertador.actualizar();
        this.setVisible(false);
    }//GEN-LAST:event_despertadorActionPerformed

    private void BanieraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BanieraActionPerformed
        // TODO add your handling code here:
        ventana_baniera.setVisible(true);
        ventana_baniera.aux = this;
        ventana_baniera.baniera = ventana_anterior.baniera;
        ventana.actualizar();
        this.setVisible(false);
    }//GEN-LAST:event_BanieraActionPerformed

    private void CafeteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CafeteraActionPerformed
        // TODO add your handling code here:
        ventana_cafetera.setVisible(true);
        ventana_cafetera.aux = this;
        ventana_cafetera.cafetera = ventana_anterior.cafetera;
        ventana_cafetera.actualizar();
        this.setVisible(false);
    }//GEN-LAST:event_CafeteraActionPerformed

    private void AspiradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AspiradorActionPerformed
        // TODO add your handling code here:
        ventana_aspirador.setVisible(true);
        ventana_aspirador.aux = this;
        ventana_aspirador.aspirador = ventana_anterior.aspirador;
        ventana_aspirador.actualizar();
        this.setVisible(false);
    }//GEN-LAST:event_AspiradorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ventana_aire.setVisible(true);
        ventana_aire.aux = this;
        ventana_aire.aire = ventana_anterior.aire;
        ventana_aire.actualizar();
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    public principal ventana_anterior;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aspirador;
    private javax.swing.JButton Atras;
    private javax.swing.JButton Baniera;
    private javax.swing.JButton Cafetera;
    private javax.swing.JButton Lampara_h3;
    private javax.swing.JButton Llave;
    private javax.swing.JButton Llave1;
    private javax.swing.JButton despertador;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lampara_cocina;
    private javax.swing.JButton lampara_h1;
    private javax.swing.JButton lampara_h2;
    private javax.swing.JButton lampara_terraza;
    private javax.swing.JButton lavadora;
    private javax.swing.JButton olla;
    private javax.swing.JButton tv;
    // End of variables declaration//GEN-END:variables
}
